### PR TITLE
Test against modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by mikehenrty** [comment]
are you still using this project @amilajack ? the repo is essentially unmaintained at this point.

**Comment by amilajack** [comment]
I'd like to use this project. I didnt know it wasn't maintained

**Comment by mikehenrty** [comment]
I would say use at your own risk. I don't think we even have travis set up for this repo anymore. That said I'll merge your PR.

**Comment by timdream** [comment]
https://github.com/mozilla/mozdownload is maintained and is used by our internal tooling.

**Comment by mikehenrty** [comment]
thanks @timdream, i'll add a note to the readme

**Comment by mikehenrty** [comment]
https://github.com/mozilla-b2g/mozilla-download/commit/fd515da2c0b73b5f83971ee56f8f6337c3732b62

**Pull request merged**
