### PR TITLE
Bug 1149178 - Support https as well.

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by gaye** [comment]
@hfiguiere I have a rewrite going at https://github.com/gaye/mozilla-download/tree/bug-1147107-taskcluster-index that will include https support

**Comment by hfiguiere** [comment]
if you think it is better, sure. It is not like things are broken.

**Comment by gaye** [comment]
@hfiguiere The rewrite makes us download stuff from the taskcluster artifact index instead of ftp.m.o. We're doing this since new automation is putting too much load on ftp.m.o (this is what caused all of the infra-related outages last week).

**Comment by hfiguiere** [comment]
Cancelled reviews and duped my bug.

**Pull request closed without merging**
